### ISSUE TITLE
CHECKLIST FOR ADDTIONAL CHANGES

### ISSUE THREAD

**Issue by ghost-012** [Larp27/PineHR#29]
### AS OF 20/04/24

1. **PROMOTION** TO ANOTHER DEPARTMENT 
2. **HISTORY** OF JOB HIRED | PROMOTED
3. **DEFAULT LEAVE TYPES AND CREDITS** GOVERNMENT MANDATED STANDARDS (MALE, FEMALE)
4. **LEAVE MONETIZATION** - CREDIT/S BALANCE NGA MA STACK UP TO RETIREMENT THAT IS CONVERTABLE TO CASH (SELECTED LEAVE TYPE)
5. **LEAVE BENEFITS** FOR EMPLOYEES (CERTAIN LEAVE TYPE LANG PWEDE MA APPLYAN BASE SA EMPLOYMENT STATUS NGA NA ASSIGN)
6. **LEAVE APPLICATION** FORM/DOCUMENT FOR APPROVAL SA HR (SIGNING)
7. **ATTENDANCE** (MORNING [AM], AFTERNOON [PM])
8. **SALARY** DEPENDS ON EMPLOYEE STATUS - PER DAILY INCOME, PER MONTH
9. PER EMPLOYEE, PER POSITION - DIFFERENT SALARY
10. DESIGNATION CONNECTED TO EMPLOYMENT STATUS

### IMPORTANT CHANGES NGA E ADD

>PROFILING

- [ ] JOB EXPERIENCE | JOB DESCRIPTION
- [ ] SEMINARS & TRAININGS
- [ ] DOCUMENTS ATTACHMENTS
- [ ] SALARY
- [ ] OTHER INFORMATION NEEDED 

> HISTORIES

- [ ] JOB HISTORIES
- [ ] ATTENDANCE
- [ ] PAYROLL
- [ ] SALARY

> MANAGEMENT

- [ ] ATTENDANCE (MORNING,AFTERNOON)
- [ ] PAYROLL (PER DAILY, PER MONTH)
- [ ] DELETE BUTTON NEEDS TO BE CHANGED | REMOVED --- TO CANCEL BUTTON 

> LEAVE APPLICATION

- [ ] STATUS CANCELLED (ONCE LEAVE APPROVED | DECLINED, CANCEL BUTTON DISAPPEARS)
- [ ] DECLINED (REMARKS WHY IT WAS DECLINED)

### FUNCTIONS NGA E PRESENT FOR MONDAY

> - [ ] JOB EXPERIENC | PROFILING

> - [ ]  SEMINARS & TRAININGS | PROFILING

> - [ ]  SALARY BASE SA POSITIONS OF EMPLOYEE | PROFILING

> - [ ]  ATTACHMENTS OR DOCUMENTS | PROFILING

> - [ ]  ATTENDANCE (MORNING, AFTERNOON)

> - [ ]  PAYROLL (PER DAILY,  PER MONTH)
